ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = POWERCARD;

CREATE TABLE MER_ACCEPTOR_POINT (
    AP_ON_ID_10           VARCHAR2(18 CHAR) NOT NULL,
    MER_ACCEPTOR_POINT_ID VARCHAR2(12 CHAR) NOT NULL,
    CONSTRAINT PK_MER_ACCEPTOR_POINT PRIMARY KEY (AP_ON_ID_10)
);

INSERT INTO MER_ACCEPTOR_POINT (
    AP_ON_ID_10,
    MER_ACCEPTOR_POINT_ID
) VALUES (
    '936000280111177646',
    '111117764535'
);

COMMIT;
